### ISSUE TITLE
tests failing with latest 8.0-4

### ISSUE THREAD

**Issue by xquery** [marklogic/python_api#32] opened 2015-09-15 13:04 UTC
latest 8.0-4 I see a bunch of tests failing, for example

```
self = <marklogic.connection.Connection object at 0x1047adda0>

    def _response(self):
        response = self.response

        if response.status_code < 300:
            pass
        elif response.status_code == 404:
            pass
        elif response.status_code == 401:
            raise UnauthorizedAPIRequest(response.text)
        else:
>           raise UnexpectedManagementAPIResponse(response.text)
E           marklogic.exceptions.UnexpectedManagementAPIResponse: {"errorResponse":{"statusCode":500, "status":"Internal Server Error", "messageCode":"MANAGE-NOGROUPWITHSERVER", "message":"MANAGE-NOGROUPWITHSERVER: (err:FOER0000) No such group with server:  group-id: 15537466737265520050 server-id: foo-xdbc", "messageDetail":{"messageTitle":"No such group with server: "}}}
```

**Comment by ndw** [comment] 2015-10-05 20:34
I can't reproduce this. Can you?

**Comment by ndw** [comment] 2015-10-09 22:18
Closing as not reproducible.

**Closed by ndw** 2015-10-09 22:18 UTC
